info/__init__.py
import logging
from logging.handlers import RotatingFileHandler
from redis import StrictRedis
from flask import Flask, g, render_template
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.wtf import CSRFProtect
from flask.ext.wtf.csrf import generate_csrf
from flask_session import Session
# flask中有一个大写Session，还有一个小写session，这三个各不相同
# flask中Session --- 将浏览器来的数据加密存cookie返回浏览器，浏览器下次带cookie来再解密
# flask中session --- 用于在视图函数中作为键值对的字典名，如session["name"] = "laowang"
# flask_session中Session --- 可以指定数据保存位置，如redis/sqlalchemy/mongodb/memcached等
from config import config


# 初始化 SQL 数据库
# Flask中很多扩展都可以先创建扩展对象，然后等初始化所需参数出现后，再调用init_app方法完成初始化
db = SQLAlchemy()
# 创建 redis 存储对象（后续在create_app函数内部，传入地址和端口，完成初始化）
redis_store = None  # type: StrictRedis  # py3.6添加新功能 --- 确保视图函数调用有智能提示！


def setup_log(environment):
    """配置日志"""
    # 设置日志的记录等级
    logging.basicConfig(level=config[environment].LOG_LEVEL)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


def create_app(environment):
    # 配置日志，传入环境名称，以便获取该环境配置中相应的日志等级
    setup_log(environment)
    # 创建Flask对象
    app = Flask(__name__)
    # 加载配置
    app.config.from_object(config[environment])
    # 传入app当参数，完成db初始化
    db.init_app(app)
    # 为redis对象指定地址和端口，完成redis对象初始化
    global redis_store
    redis_store = StrictRedis(host=config[environment].REDIS_HOST,
                              port=config[environment].REDIS_PORT,
                              decode_responses=True)  # redis中取出的value默认binary格式，设置解码将其转换回string。

    # 添加自定义过滤器
    from info.utils.common import do_index_class
    app.add_template_filter(do_index_class, "index_class")

    # 开启当前项目 CSRF 保护（只做验证，cookie中csrf_token和表单中csrf_token需要手动实现）
    CSRFProtect(app)
    # 上一行帮我们做了：从cookie中取出随机值，从表单中取出随机值，然后校验，并响应校验结果
    # 我们还需要做：
    # 1. 在返回响应时往cookie中添加一个csrf_token。
    # 2. 在表单中添加隐藏的csrf_token。因我们现在使用的是ajax请求，而非传统表单，故需在ajax请求时，带上csrf_token随机值。

    from info.utils.common import user_login_data  # 用之前再导入，否则循环导入报错

    @app.errorhandler(404)  # 统一捕获所有404，并返回自定义404页面
    @user_login_data
    def page_not_found(e):  # e 接收报错传入的参数“404 NOT FOUND”
        user = g.user
        data = {
            "user": user.to_dict() if user else None
        }
        return render_template("news/404.html", data=data)

    @app.after_request
    def after_request(response):
        csrf_token = generate_csrf()  # flask.ext.wtf.csrf中一个模块，用于专门生成csrf_token值
        response.set_cookie("csrf_token", csrf_token)
        return response

    # 设置用Session将 app 中数据保存到指定位置
    Session(app)

    # 注册网站首页蓝图。导入蓝图小心import死循环！紧挨着注册行导入！
    from info.modules.index import index_blu
    app.register_blueprint(index_blu)

    # 注册登录注册模块的蓝图
    from info.modules.passport import passport_blu
    app.register_blueprint(passport_blu)

    # 注册新闻模块的蓝图
    from info.modules.news import news_blu
    app.register_blueprint(news_blu)

    # 注册用户profile模块的蓝图
    from info.modules.profile import profile_blu
    app.register_blueprint(profile_blu)

    # 注册后台管理admin模块的蓝图
    from info.modules.admin import admin_blu
    app.register_blueprint(admin_blu, url_prefix="/admin")

    return app

info/libs/__init__.py
# 第三方提供的一些SDK，放在当前文件夹下

info/modules/__init__.py
# modules模块，用于保存项目所有的业务逻辑模块，比如：首页、新闻详情页、个人中心、后台管理etc

info/modules/admin/__init__.py
# 后台管理 admin 模块的蓝图

from flask import Blueprint, redirect, request, session, url_for

# url前缀也可在将蓝图注册进app时添加
admin_blu = Blueprint("admin", __name__)

from . import views


@admin_blu.before_request
def check_admin():
    if not request.url.endswith(url_for("admin.login")):  # 加上此行，否则后台登录页面都打不开！！
        is_admin = session.get("is_admin", False)
        if not is_admin:
            return redirect("/")

info/modules/admin/views.py
import time
from flask import current_app, redirect, render_template, request, session, g, jsonify
from datetime import datetime, timedelta
from info import constants, db
from info.models import User, News, Category
from info.utils.common import user_login_data
from info.utils.image_storage import storage
from info.utils.response_code import RET
from . import admin_blu


@admin_blu.route("/news_type", methods=["GET", "POST"])
def news_type():
    if request.method == "GET":
        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
            return render_template("admin/news_type.html", errmsg="数据库查询失败")
        if not categories:
            return render_template("admin/news_type.html", errmsg="未查到新闻分类")
        categories = [category.to_dict() for category in categories[1:]]  # 扔掉“最新”
        return render_template("admin/news_type.html", data={"categories": categories})
    else:
        category_name = request.json.get("name")
        category_id = request.json.get("id")
        if not category_name:
            return jsonify(errno=RET.PARAMERR, errmsg="类别名称不能为空")
        if category_id:  # category_id非空，说明是【修改已有类别】操作
            try:
                category_id = int(category_id)
            except Exception as e:
                current_app.logger.error(e)
                return jsonify(errno=RET.PARAMERR, errmsg="类别id必须为整数")
            try:
                category = Category.query.get(category_id)
            except Exception as e:
                current_app.logger.error(e)
                return jsonify(errno=RET.DBERR, errmsg="数据库查询失败")
            if not category:
                return jsonify(errno=RET.NODATA, errmsg="该id对应的类别不存在")
            category.name = category_name
        else:  # category_id为空，说明是【增加一个新类别】操作
            if Category.query.filter(Category.name == category_name).count() > 0:
                return jsonify(errno=RET.PARAMERR, errmsg="拟添加类别已存在")
            category = Category()
            category.name = category_name
            db.session.add(category)
        return jsonify(errno=RET.OK, errmsg="新闻类别修改/新增成功")


@admin_blu.route("/news_edit_detail", methods=["GET", "POST"])
def news_edit_detail():
    if request.method == "GET":  # 点击【编辑】按钮打开页面是GET请求，此时需将该条新闻内容返回前端供渲染显示！！！
        news_id = request.args.get("news_id", None)
        if not news_id:
            return render_template("admin/news_edit_detail.html", data={"errmsg": "news_id不能为空"})
        try:
            news_id = int(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return render_template("admin/news_edit_detail.html", data={"errmsg": "news_id必须为整数"})
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return render_template("admin/news_edit_detail.html", data={"errmsg": "数据库查询失败"})
        if not news:
            return render_template("admin/news_edit_detail.html", data={"errmsg": "该id对应的新闻不存在"})
        try:
            categories = Category.query.all()  # 需将所有类别都返回供渲染，因管理员需要看到类别下拉框中的所有类别！
        except Exception as e:
            current_app.logger.error(e)
            return render_template("admin/news_edit_detail.html", data={"errmsg": "数据库查询失败"})
        categories_filtered = []
        for category in categories[1:]:  # 【最新】类别无需返回给前端
            category_dict = category.to_dict()
            category_dict["is_selected"] = False
            if category.id == news.category_id:  # 遍历类别时，如果某类别恰是该新闻所属类别，则为其标示【选中】
                category_dict["is_selected"] = True  # 前端渲染该新闻时，类别下拉框应默认显示该新闻当前所属类别！
            categories_filtered.append(category_dict)
        data = {
            "news": news.to_dict(),
            "categories": categories_filtered
        }
        return render_template("admin/news_edit_detail.html", data=data)
    else:  # 当管理员完成该新闻版式编辑，点击【提交】按钮是POST请求，此时需从前端取出各改后参数，并更新数据库中该新闻各属性！
        news_id = request.form.get("news_id", None)
        title = request.form.get("title", None)
        category_id = request.form.get("category_id", None)
        digest = request.form.get("digest", None)
        index_image = request.files.get("index_image", None)  # 此参数可以为空，表示仍使用原图片
        content = request.form.get("content", None)
        if not all([news_id, title, category_id, digest, content]):
            return jsonify(errno=RET.PARAMERR, errmsg="参数有误")
        try:
            news_id = int(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.PARAMERR, errmsg="news_id必须为整数")
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库查询失败")
        if not news:
            return jsonify(errno=RET.NODATA, errmsg="该id对应的新闻不存在")
        news.title = title
        news.category_id = category_id
        news.digest = digest
        news.content = content
        if index_image:  # 如果此参数有值，说明需要更换图片
            try:
                index_image = index_image.read()  # 先尝试读取图片
            except Exception as e:
                current_app.logger.error(e)
                return jsonify(errno=RET.PARAMERR, errmsg="参数有误")
            try:
                key = storage(index_image)  # 再将图片上传到七牛云
            except Exception as e:
                current_app.logger.error(e)
                return jsonify(errno=RET.THIRDERR, errmsg="上传图片失败")
            news.index_image_url = constants.QINIU_DOMIN_PREFIX + key
        return jsonify(errno=RET.OK, errmsg="新闻版式编辑成功")


@admin_blu.route("/news_edit")  # 除【url/视图函数名/filter内容/basic_dict/模板名】外，和news_review视图函数完全一样
def news_edit():
    page = request.args.get("page", 1)
    keywords = request.args.get("keywords", None)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1
    filters = [News.status == 0]  # 仅显示【审核通过】的新闻
    if keywords:
        filters.append(News.title.contains(keywords))
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc())\
                             .paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)
        current_page = paginate.page
        total_page = paginate.pages
        current_page_news = paginate.items
    except Exception as e:
        current_app.logger.error(e)
        current_page = 1
        total_page = 1
        current_page_news = []
    context = {
        "current_page": current_page,
        "total_page": total_page,
        "current_page_news": [news.to_basic_dict() for news in current_page_news]
    }
    return render_template("admin/news_edit.html", data=context)


@admin_blu.route('/news_review_action', methods=["POST"])  # 两视图函数可合并，通过GET/POST区分彼此
def news_review_action():
    news_id = request.json.get("news_id", None)
    action = request.json.get("action", None)
    if not news_id or action not in ["accept", "reject"]:
        return jsonify(errno=RET.PARAMERR, errmsg="参数格式错误")
    try:
        news_id = int(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="news_id必须为整数")
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库查询失败")
    if not news:
        return jsonify(errno=RET.NODATA, errmsg="未查询到该id对应新闻")
    if action == "accept":
        news.status = 0
    else:
        reason = request.json.get("reason", None)
        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg="请输入审核未通过原因")
        news.status = -1
        news.reason = reason
    return jsonify(errno=RET.OK, errmsg="新闻审核完成")


@admin_blu.route('/news_review_detail/<int:news_id>')
def news_review_detail(news_id):
    try:
        news_id = int(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return render_template("admin/news_review_detail.html", data={"errmsg": "参数必须为整数"})
    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
    if not news:
        return render_template("admin/news_review_detail.html", data={"errmsg": "未查询到此新闻"})
    return render_template("admin/news_review_detail.html", data={"news": news.to_dict()})


@admin_blu.route("/news_review")
def news_review():
    page = request.args.get("page", 1)
    keywords = request.args.get("keywords", None)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1
    filters = [News.status != 0]  # 仅显示【审核中】和【审核未通过】的新闻
    if keywords:
        filters.append(News.title.contains(keywords))
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc())\
                             .paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)
        current_page = paginate.page
        total_page = paginate.pages
        current_page_news = paginate.items
    except Exception as e:
        current_app.logger.error(e)
        current_page = 1
        total_page = 1
        current_page_news = []
    context = {
        "current_page": current_page,
        "total_page": total_page,
        "current_page_news": [news.to_review_dict() for news in current_page_news]
    }
    return render_template("admin/news_review.html", data=context)


@admin_blu.route("/user_list")
def user_list():
    page = request.args.get("page", 1)  # 对于用url传入参数的GET请求，使用args去获取参数
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1
    try:
        paginate = User.query.filter(User.is_admin == False).order_by(User.last_login.desc())\
                             .paginate(page, constants.ADMIN_USER_PAGE_MAX_COUNT, False)
        current_page = paginate.page

info/modules/index/__init__.py
# 1.导入蓝图包
from flask import Blueprint

# 2.创建蓝图对象
index_blu = Blueprint("index", __name__)

# 4.将用蓝图注册路由装饰过的视图函数导回
from . import views

# 5.将蓝图注册添加到create_app函数中

info/modules/index/views.py
# 3.导入蓝图对象，并用它注册路由，装饰视图函数
from flask import render_template, current_app, request, jsonify, g
from info import constants
from info.models import News, Category
from info.utils.common import user_login_data
from info.utils.response_code import RET
from . import index_blu


@index_blu.route('/news_list')
def news_list():

    # 1. 获取url中？后面的参数：新闻分类cid，页码page，每页条数per_page
    cid = request.args.get("cid", "1")
    page = request.args.get("page", "1")
    per_page = request.args.get("per_page", constants.HOME_PAGE_MAX_NEWS)

    # 2. 校验参数
    try:
        cid = int(cid)
        page = int(page)
        per_page = int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

    # 3. 查询数据
    filters = [News.category_id==cid] if cid != 1 else []  # cid=1表示“最新”新闻，无需过滤。。。而cid=2,3,4……才需要过滤
    filters.append(News.status == 0)  # 只有通过审核的新闻，才会被公开显示。status=1审核中，status=-1审核不通过
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据查询错误")

    # 4. 通过paginate对象获取：当前页码、总页数、当前页的所有新闻列表
    current_page = paginate.page
    total_page = paginate.pages
    current_page_news = paginate.items
    current_page_news = [news.to_basic_dict() for news in current_page_news]

    # 5. 生成数据并返回
    data = {
        "current_page": current_page,
        "total_page": total_page,
        "current_page_news": current_page_news,
    }

    return jsonify(errno=RET.OK, errmsg="OK", data=data)


@index_blu.route('/')
@user_login_data
def index():
    # 右上角功能区的实现：【登录/注册】or【用户头像/昵称/退出】
    # user_id = session.get("user_id", None)  # 尝试获取当前登录用户的user_id
    # user = None  # 先定义，保证后续data中的使用不会报 undefined error
    # if user_id:
    #     try:
    #         user = User.query.get(user_id)  # 通过 user_id 获取用户信息
    #     except Exception as e:
    #         current_app.logger.error(e)
    user = g.user

    # 右侧新闻点击排行功能的实现
    top_click_news = []
    try:
        top_click_news = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)
    top_click_news = [news.to_basic_dict() for news in top_click_news]  # 每条新闻从对象转字典，方便前端调用

    # 左侧新闻列表的实现由【'/news_list'】路由实现
    # 顶端新闻分类功能的实现
    categories = []
    try:
        categories = Category.query.all()
    except Exception as e:
        current_app.logger.error(e)
    categories = [category.to_dict() for category in categories]

    # 把数据进行汇总，当参数传给模板，供渲染时使用
    data = {
        "user": user.to_dict() if user else None,  # 将user转为字典形式传给前端html模板，供 js 分支判断使用
        "top_click_news": top_click_news,
        "categories": categories,
    }
    return render_template('news/index.html', data=data)


# 在打开网页时，浏览器会默认去请求【根路径+favicon.ico】作为网站标签的小图标
# send_static_file是flask提供的查找指定静态文件的方法
@index_blu.route('/favicon.ico')
def favicon():
    return current_app.send_static_file('news/favicon.ico')

info/modules/news/__init__.py
# 新闻详情模块的蓝图

from flask import Blueprint

news_blu = Blueprint("news", __name__, url_prefix="/news")

from . import views

info/modules/passport/__init__.py
# 登录和注册模块的所有视图函数在此package内实现

from flask import Blueprint

passport_blu = Blueprint("passport", __name__, url_prefix="/passport")

from . import views

info/modules/profile/__init__.py
# 用户profile详情模块的蓝图

from flask import Blueprint

profile_blu = Blueprint("profile", __name__, url_prefix="/user")

from . import views

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    {% block cssBlock %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block scriptBlock %}{% endblock %}
</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
            {% block categoryBlock %}{% endblock %}
            {% if data.user %}  <!--如果user不等于None，那么说明当前存在已登录用户，故需加载用户头像和昵称，显示到右上角-->
                <div class="user_login fr">
                    <img src="{% if data.user.avatar_url %}
                                    {{ data.user.avatar_url }}
                              {% else %}
                                    ../../static/news/images/person01.png
                              {% endif %}"
                    class="lgin_pic">  <!--如果该登录用户有头像url，则使用之。如果没有，则使用默认的头像url-->
                    <a href="/user/info" id="nick_name">{{ data.user.nick_name }}</a>
                    <a href="javascript:;" onclick="logout()">退出</a>  <!--点击触发logout函数，其内执行location.reload()-->
                </div>
            {% else %}
                <div class="user_btns fr">  <!--如果没有登录用户，则显示【登录】和【注册】按钮-->
                    <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="conter_con">
        {% block contentBlock %}{% endblock %}
        {% block rankblock %}
            <div class="rank_con fr">
                {% block authorBlock %}{% endblock %}
                <div class="rank_title">
                    <h3>点击排行</h3>
                </div>
                <ul class="rank_list">
                    {% for news in data.top_click_news %}  <!--用【管道+自定义过滤器】设定前三名class分别为first/second/third-->
                        <li><span class = {{ loop.index | index_class }}>{{ loop.index }}</span><a href="#">{{ news.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        {% endblock %}

    </div>

    {% block bottomBlock %}
        <div class="footer">
            <div class="footer_links">
                <a href="">关于我们</a><span>|</span><a href="">联系我们</a><span>|</span><a href="">招聘人才</a><span>|</span><a href="">友情链接</a>
            </div>
            <p class="copyright">
                CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
                电话：010-****888    京ICP备*******8号
            </p>
        </div>
    {% endblock %}

    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

info/templates/news/index.html
{% extends "news/base.html" %}

{% block titleBlock %}
首页-新经资讯
{% endblock %}

{% block scriptBlock %}  <!--index.js负责新闻列表向下滚动刷新-->
<script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}

{% block categoryBlock %}  <!--只有首页才有category模块-->
<ul class="menu fl">  <!--menu fl类，控制不同类按钮被点击后，局部刷新操作-->
    {% for category in data.categories %}
        {% if loop.index == 1 %}
            <li class="active" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
        {% else %}
            <li data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock %}

{% block contentBlock %}
<ul class="list_con fl"> <!--index.js用for循环实现新闻列表-->
</ul>
{% endblock %}

info/templates/news/user.html
{% extends "news/base.html" %}

{% block titleBlock %}
用户中心
{% endblock %}

{% block contentBlock %}
<div class="user_menu_con fl">
    <div class="user_center_pic">
        <img src={% if data.user.avatar_url %}
            {{ data.user.avatar_url }}
        {% else %}
            "../../static/news/images/user_pic.png"
        {% endif %} alt="用户图片">
    </div>
    <div class="user_center_name">{{ data.user.nick_name }}</div>
    <ul class="option_list">  <!-- url_for("profile.base_info") 等价于 "/user/base_info" -->
        <li class="active"><a href="/user/base_info" target="main_frame">基本资料</a></li>
        <li><a href="{{ url_for("profile.pic_info") }}" target="main_frame">头像设置</a></li>
        <li><a href="{{ url_for("profile.user_follow") }}" target="main_frame">我的关注</a></li>
        <li><a href="{{ url_for("profile.pass_info") }}" target="main_frame">密码修改</a></li>
        <li><a href="{{ url_for("profile.user_collection") }}" target="main_frame">我的收藏</a></li>
        <li><a href="{{ url_for("profile.news_release") }}" target="main_frame">新闻发布</a></li>
        <li><a href="{{ url_for("profile.news_list") }}" target="main_frame">新闻列表</a></li>
    </ul>
</div>
<div class="user_con fr">
    <iframe src="/user/base_info" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
</div>
{% endblock %}

{% block rankblock %}  <!--清空rankblock中默认显示的排行榜内容-->
{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
{% endblock %}

info/templates/news/user_base_info.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
	<link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/user_base_info.js"></script>
</head>
<body class="inframe_body">
    <form class="base_info">
        <h3>基本资料</h3>
        <div class="form-group">
            <label>个性签名：</label>
            <input id="signature" type="text" name="signature" class="input_txt" value="{{ data.user.signature }}">
        </div>
        <div class="form-group">
            <label>用户昵称：</label>
            <input id="nick_name" type="text" name="" class="input_txt" value="{{ data.user.nick_name }}">
        </div>
        <div class="form-group">
            <label>性别：</label>
            <input class="gender" type="radio" name="gender" value="MAN" checked="checked"> <b>男</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <input class="gender" type="radio" name="gender" value="WOMAN">  <b>女</b>
        </div>
        <div class="form-group">
            <input type="submit" value="保 存" class="input_sub">
        </div>
    </form>
</body>
</html>